### ISSUE TITLE
Add a page to select a position

### ISSUE THREAD

**Issue by niallwingham** [Infusion-Labs/portal#20]
Page should list open positions, optionally based on certain locations/industries/technologies.  After selecting one user should probably be taken to the apply page.

If the user got to the apply page through another path and hadn't selected a position, they could be brought to this page after submitting their video, to refine their application.

**Comment by asanabia** [comment]
But Niall, I thought the only position was "Consultant" :)

**Comment by freemancw** [comment]
At least fulltime/intern select on apply. Look at adam's notes.
