### ISSUE TITLE
Clicking on bookshelf should transition camera closer to bookshelf

### ISSUE THREAD

**Issue by freemancw** [Infusion-Labs/portal#29]
When the user is in the `overview` state and they click on the bookshelf, two things should happen:

1. The camera should zoom in and focus on the bookshelf such that it takes up the majority of the canvas.
2. After (1) completes, we should initiate a ui-router `$state.go` event to transition the application to the `overview.locations` state.

The `OfficeSceneService` should be responsible for executing the camera transition, but not the `$state` transition. The method should return a promise against which the client can program.   

##### Additional info and recommended reading

* The scene model is located in `src/app/assets/models/office.obj`. OBJ files are plain-text, so you can open it in Sublime.
* Use `SplineCurve3` class from `THREE` to define camera path. See the [API](http://threejs.org/docs/#Reference/Extras.Curves/SplineCurve3) and [this example](http://threejs.org/examples/webgl_geometry_extrude_splines.html).
* Make camera travel along `SplineCurve3` (position is easy, forward should be tangent, up should be normal.)
* Good stuff on splines: http://cagd.cs.byu.edu/~557/text/ch6.pdf

**Comment by asanabia** [comment]
Leaving this here for convenience, the find and replace regex for the .obj file to generate the names in we need it again in the future.
Find: (#\s*\n#\s*object\s(\w*)\n#)
Replace: \1\no \2

**Comment by asanabia** [comment]
The camera should transition to each place in the office it needs to go. Note that right now there's no way back- but also no valid transition states at the moment, so you can just click again to reset the animation / click something else.

Its set up so the state transition in the controller doesn't happen until after the animation is complete. I'm gonna let you look at it / approve it before I close this issue.

**Comment by freemancw** [comment]
Closing this, listed minor improvement to service in issue #39 . Placing regex in wiki for future reference. Will open new issue for backwards navigation.
