### ISSUE TITLE
Can't import fs module in Typescript

### ISSUE THREAD

**Issue by asanabia** [Infusion-Labs/portal#38]
After many many different attempts and lots of research, I still can't figure out how to access the filesystem using our technology stack. When I use

import fs = require('fs-extra');

I get a compiler error because it can't reference fs-extra, despite me adding its path to the reference file. When I use

import fs = require('fs');

After adding the node typescript module to references, I get this error:
![err](https://cloud.githubusercontent.com/assets/1928286/5761874/586c4742-9cac-11e4-8606-f8b4c5b7c41c.PNG)
from this generated javascript:
![js1](https://cloud.githubusercontent.com/assets/1928286/5761881/633e535e-9cac-11e4-8ebd-39878bc590e9.PNG)
Angular can't recognize the controller properly because of how typescript is translating it to js

I also tried replacing the import statement with

var fs: ng.IModule = require('fs');

To try to solve the issue, but I get the previous error as well as a new one:
![err2](https://cloud.githubusercontent.com/assets/1928286/5761903/98b82a82-9cac-11e4-993a-a0d10e69337a.PNG)
which comes from require.js I added as a script on the index.html page, which was what let me get require statements working at all (before it just said "require" was undefined). I get this javascript:
![js2](https://cloud.githubusercontent.com/assets/1928286/5761923/b64c19b4-9cac-11e4-8342-0d8f84cc3519.PNG)
Which looks more accurate, but still won't load the 'fs' module

Maybe this will help one of you guys figure this out, or find an alternative. I've never had so much trouble with a single line of code in my life Q_Q

**Comment by niallwingham** [comment]
Yeah, no kidding!  It's great that you've puzzled over this for a while,
but it's no good to stay stuck on something for too long...  I would move
on to a new task at this point (I know Clinton was drawing up a whole
list--bug him if he hasn't put them on GitHub yet).

MetLife is keeping me pretty busy but I'll take a look at it over the
weekend.  Maybe we'll just end up a few angular services in raw JavaScript
whenever something needs to require an NPM module.

**Comment by asanabia** [comment]
Yeah, I think for now I'll work on the OfficeScene directive issue, though before I do I have a pluralsight video in mind on it that I want to watch first that I think will make it go much smoother than me just googling every problem I run into. But if there's something more pressing let me know!

**Comment by freemancw** [comment]
It seems to me that this is a "trying to use node package in the client" problem not a typescript problem. require should work in node-webkit, but NOT in normal browsers (chrome, firefox...).

**Comment by freemancw** [comment]
Fixed package.json to point node-webkit to build and not src. Now, you just need:

1. add the following line to references.ts
/// <reference path="../../bower_components/DefinitelyTyped/node/node.d.ts" />

2. inside applyCtrl:
var fs = require('fs');



these changes should work when you run the program with node-webkit, but we would need something like browserify if we want to keep supporting browsers

**Comment by niallwingham** [comment]
Hahaha... good catch Clinton!
