### ISSUE TITLE
OfficeSceneService moveCamera should return promise

### ISSUE THREAD

**Issue by freemancw** [Infusion-Labs/portal#39]
The current implementation of moving the camera uses a callback to perform work after the TWEEN is complete. Instead, the method should return an angular promise against which the client can program.

**Comment by asanabia** [comment]
I'll get on that- I actually didn't know that a "promise" was an actual type in angular until about 2pm yesterday XD hence my misunderstanding of the initial issue

**Comment by asanabia** [comment]
moveCamera now returns a promise that is fulfilled when the camera finishes moving. overviewCtrl modified to reflect this change
