### ISSUE TITLE
Clicking on home should animate transition to overview state

### ISSUE THREAD

**Issue by freemancw** [Infusion-Labs/portal#48]
Currently, when the user clicks on Home, they are transitioned to the overview state, but no animations play to indicate a transition. Instead, the camera should transition backward out of whatever it was looking at to return to its original overview position.

- [x] Technologies
- [x] Technology details
- [x] Industries
- [x] Industry details
- [x] Locations
- [x] Location details
- [x] Apply

**Comment by asanabia** [comment]
Right now the pop-up on Apply still stays while the camera transitions back
