### ISSUE TITLE
Glowy outline for clickable objects

### ISSUE THREAD

**Issue by asanabia** [Infusion-Labs/portal#69]
To draw attention to clickable objects in the scene by giving them some kind of glowy outline (three.js shader?) Also add plaque 3D labels next to clickable objects

**Comment by asanabia** [comment]
Update on this issue:
I spent quite a while trying to get the GeometricGlowMesh library (which was the only one I found that was easy to add to the project) to work with our OBJ file. Here's what progress I've made:

- The "usemtl" tags in the .OBJ that assign a material to a set of faces, for whatever reason, breaks that set of faces into a separate child object when its being loaded.
- I've readd, though not confirmed, that the OBJMTLLoader has some issues with non-triangular faces and that triangulating faces on export is recommended.
- Faces in the OBJ file must be listed with normals for the module to work, which is the third segment in a face line, i.e.:
`f 115/122/108 116/123/109 117/124/110` <-- 110 denotes the index of the vertex normal at this point
If they have no materials it looks like
`f 115//108 116//109 117//110` (note the double slash in the middle)

**Comment by asanabia** [comment]
Just found this link:
https://github.com/mrdoob/three.js/issues/5598
Which details the problem I'm having. Basically the OBJMTLLoader breaks faces after a "usemtl" tag into new unnamed objects at the same level as its supposed-to-be-parent. Going to try to use this example as a solution

**Comment by asanabia** [comment]
Here's the current state:
http://i.imgur.com/k7XVb9J.jpg
- The balloon looks fine
- The map doesn't glow at all
- The box looks weird, partially because of awkward normals I think
- The bear, since its all one object now, has glowy spheres around its eyes and nose and a glowy mustashe because of its mouth

I have an idea or two left of where to go from here with this implementation, but I think for the rest of the day I'll be investigating geometry shaders in three js

**Comment by asanabia** [comment]
For reference, here's what the new model looks like with glow. Better, but still not great:
![image](https://cloud.githubusercontent.com/assets/1928286/6330530/16b5645a-bb47-11e4-900a-59a7552adaf3.png)
As I mentioned earlier, we might wanna drop the glow meshes in favor of a simple text prompt for time / effort reasons.

**Comment by freemancw** [comment]
Closing this for now - may investigate if it comes up again in user testing.
