### ISSUE TITLE
Improve layout and styling for Apply modal

### ISSUE THREAD

**Issue by freemancw** [Infusion-Labs/portal#86]
The attached images are mockups that provide guidance for how the Apply modal states should look. Note that they lack forward/backward buttons - these should probably just be simple text links. Facebook is a good place to find images for these.

Since we are not displaying much content, it is important that font sizes are larger and we make good use of padding.

![apply-feedback](https://cloud.githubusercontent.com/assets/413362/6355245/90b0fbd0-bc22-11e4-8ab7-8570f1bf974d.png)

- [x] Padding in the image is about 32px. This padding should be equal to the gutters between the images and the text section. 
- [x] Titles have all words capitalized, no period
- [x] Subtitles have all words capitalized, no period
- [x] The top of the title aligns with the top of the first image. The "X" has no content in its row.
- [x] There should be exactly 2 images 
- [ ] Each image should have an aspect ratio of 4:3. 
- [x] Minimum acceptable resolution is 640x480. All images should have very close to the same resolution if not exactly the same resolution. Prefer a standard or commonly used resolution.
- [x] Use only one accent color: official Infusion blue #094d80. 
- [x] Images do not use dropshadow.
- [x] Paragraph font should be different from header font. The image displays the official infusion font, Univers STD. 
- [x] Arrows are the same

![apply-mockup-1](https://cloud.githubusercontent.com/assets/413362/6323706/d77ac568-bafc-11e4-8901-bb84ac55e342.png)
![apply-mockup-2](https://cloud.githubusercontent.com/assets/413362/6323799/5fdd493e-bafe-11e4-863d-14ec339f2808.png)

**Comment by goodhanded** [comment]
What happened to the Next and Previous buttons?

**Comment by goodhanded** [comment]
Oh, I just noticed your comment about the buttons in your description.

**Comment by goodhanded** [comment]
Images are 960x640.

**Comment by goodhanded** [comment]
Regarding "Use only one accent color: official Infusion blue #094d80.": Currently the buttons are blue and the background of the body in the application page is a different shade of blue. If these are both supposed to be the same color, and we want to keep the next and previous buttons, then what color should those buttons be? Surely you don't want them to be the same.

**Comment by goodhanded** [comment]
Regarding "Each image should have an aspect ratio of 4:3.": Currently these aspect ratios are fluid in order to allow the page to be flexible while keeping the proportions of the two halves of the page constant. I can fix the aspect ratios, but in order to do so, the ratio of the body width to the image width will have to be variable. This could result in one half of the page being oversized compared to the other, depending upon the dimensions of the viewport. Is the aspect ratio of the images more important than the proportion of these areas?

**Comment by freemancw** [comment]
The aspect ratio of the images is more important than the proportion between the left and right columns. The images height should be calculated such that there is an exact spacing between them and the bottom of the second image respects the 32px padding on the whole modal. The widths are a derivative value that is not specified. The left-hand side content should just take up as much room as it can while respecting the 32px gutter.

**Comment by freemancw** [comment]
I see what you're saying about the buttons, which I why I originally mentioned they should probably be text links. Making them text links sidesteps the issue.
